apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWUyMg==
  mongo-root-password: cGFzc3dvcmQyMg==
---
apiVersion: v1
kind: Secret
metadata:
  name: mongoexpress-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWUyMg==
  mongo-root-password: cGFzc3dvcmQyMg==